apiVersion: v1
kind: ReplicationController
metadata:
  name: firstreplicationcontroller
  labels:
    app: voatingapp
spec:
  replicas: 1 
  selector:
  template:
    metadata:
      name: firstrcpod
      labels:
        type: app
    spec:
      containers:
        - name: firstcontainer
          image: nginx

